- .github/workflows/build.yml
> chore: Fixes CI (publish job)

- .github/workflows/build.yml
> ci: Fixes publish job

- .github/workflows/build.yml
- images/vct/Dockerfile
> ci: Multi arch build

- images/vct/Dockerfile
> ci: Fixes multi arch build

- .github/workflows/build.yml
> ci: Removes macos

- .github/workflows/build.yml
> ci: Fix docker build-args values

- .github/workflows/build.yml
> ci: Fix docker image URL

- .github/workflows/publish.yaml
- images/vct/Dockerfile
> ci: Adds release publish job

- .github/workflows/build.yml
- .github/workflows/publish.yaml
> ci: Adds macos unit tests

- test/bdd/features/rest_controller.feature
- test/bdd/pkg/controller/rest/rest_controller_steps.go
- test/bdd/pkg/controller/rest/testdata/bachelor_degree_of_arts_no_proof.json
- test/bdd/pkg/controller/rest/testdata/bachelor_degree_of_finance_no_proof.json
- test/bdd/pkg/controller/rest/testdata/bachelor_degree_of_law_no_proof.json
- test/bdd/pkg/controller/rest/testdata/bachelor_degree_of_science_no_proof.json
- test/bdd/pkg/controller/rest/testdata/verifiable_credentials_no_proof.json
> test: Adds BDD tests

- .github/workflows/publish.yaml
- Makefile
> ci: Upload binaries to github release

- Makefile
- pkg/client/vct/client.go
- pkg/client/vct/client_test.go
- pkg/controller/rest/operation.go
- test/bdd/pkg/controller/rest/rest_controller_steps.go
> feat: Adds REST client

- pkg/controller/command/command.go
- pkg/controller/command/command_test.go
> fix: Fixes signature response

- cmd/vct/startcmd/start_test.go
- test/bdd/bddtests_test.go
> refactor: Tests have a different pkg name

- .gitignore
- Makefile
- pkg/client/vct/client_test.go
- pkg/controller/command/command_test.go
- pkg/controller/rest/operation_test.go
> refactor: Adds go generate for mocks

- pkg/client/vct/client.go
- pkg/client/vct/client_test.go
- pkg/controller/command/command.go
- test/bdd/features/rest_controller.feature
- test/bdd/pkg/controller/rest/rest_controller_steps.go
> feat: Adds helper function to calculate leaf hash

- cmd/vct/startcmd/start.go
- cmd/vct/startcmd/start_test.go
- go.mod
> feat: Creates test tree (for development)

- cmd/vct/startcmd/start.go
> fix: Init log by tree id

- pkg/controller/rest/operation.go
- pkg/controller/rest/operation_test.go
> feat: Adds healthcheck endpoint

- .github/workflows/build.yml
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
> ci: bump semver when publishing snapshot

- cmd/vct/startcmd/start.go
- pkg/client/vct/client_test.go
- pkg/context/loader/context.go
- pkg/controller/command/command_test.go
- test/bdd/pkg/controller/rest/rest_controller_steps.go
> feat: Removes remote document loader

- README.md
> chore: add readme tags

- .github/workflows/publish.yaml
> chore: setup go 1.16 for release job

- images/vct/Dockerfile
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
> chore: add docker label

- Makefile
> chore: gzip vct binaries

- Makefile
> fix: gzip binaries

- .github/workflows/publish.yaml
- Makefile
> ci: Fixes binaries

- .github/workflows/publish.yaml
> ci: Increased timeout

- cmd/vct/startcmd/start.go
- cmd/vct/startcmd/start_test.go
- pkg/client/vct/client.go
- pkg/controller/command/command.go
- pkg/controller/command/command_test.go
- pkg/controller/command/models.go
- pkg/controller/rest/operation.go
- pkg/controller/rest/operation_test.go
- test/bdd/features/rest_controller.feature
- test/bdd/fixtures/vct/docker-compose.yml
- test/bdd/pkg/controller/rest/rest_controller_steps.go
> feat: Multi log support

- pkg/client/vct/client.go
- pkg/controller/command/command.go
- pkg/controller/command/command_test.go
- pkg/controller/command/models.go
- pkg/controller/rest/operation.go
- pkg/controller/rest/operation_test.go
- test/bdd/features/rest_controller.feature
- test/bdd/fixtures/vct/docker-compose.yml
- test/bdd/pkg/controller/rest/rest_controller_steps.go
> feat: Context support for multi-tenancy usage

- cmd/vct/startcmd/start.go
- pkg/client/vct/client.go
- pkg/client/vct/client_test.go
- pkg/controller/command/command.go
- pkg/controller/command/command_test.go
- pkg/controller/command/models.go
- pkg/controller/rest/operation.go
- pkg/controller/rest/operation_test.go
- test/bdd/fixtures/vct/docker-compose.yml
- test/bdd/pkg/controller/rest/rest_controller_steps.go
Webfinger response.
`curl https://vct.com/maple2021/.well-known/webfinger`
```
{
"subject":"https://vct.com/maple2021",
"properties":{
"https://trustbloc.dev/ns/ledger-type":"vct-v1",
"https://trustbloc.dev/ns/public-key":"cHVibGljIGtleQ=="
},
"links":[
{
"rel":"self",
"href":"https://vct.com/maple2021"
}
]
}
```
> feat: Webfinger support

- cmd/vct/startcmd/start.go
- cmd/vct/startcmd/start_test.go
- test/bdd/fixtures/vct/docker-compose.yml
- test/bdd/fixtures/vct/nginx-config/nginx.conf
> feat: Adds load balancer to demonstrate horizontal scaling

- .gitignore
- Makefile
- README.md
- cmd/vct/main.go
- cmd/vct/startcmd/start.go
- go.mod
- pkg/controller/rest/models.go
- pkg/controller/rest/operation.go
- scripts/generate_test_keys.sh
- test/bdd/bddtests_test.go
- test/bdd/features/rest_controller.feature
- test/bdd/fixtures/vct/docker-compose.yml
- test/bdd/fixtures/vct/nginx-config/nginx.conf
> docs: Adds docs for the service.

- cmd/vct/startcmd/start.go
- pkg/controller/command/command.go
- pkg/controller/command/command_test.go
> fix: Returns an error when public key is empty

- test/bdd/fixtures/vct/docker-compose.yml
> chore: Removes mysql

- README.md
> docs: Configauration and startup options

- README.md
- cmd/vct/startcmd/start.go
- pkg/controller/rest/operation.go
- pkg/controller/rest/operation_test.go
> feat: Adds metrics

- README.md
- cmd/vct/startcmd/start.go
> feat: Adds metrics endpoint

- go.mod
- go.sum
> chore: Updates json-gold module

- cmd/internal/serverutil/serverutil.go
Signed-off-by: Derek Trider <Derek.Trider@securekey.com>
> fix: Handle additional race condition with multiple servers

- README.md
- cmd/vct/startcmd/start.go
- internal/pkg/ldcontext/ldcontext.go
- pkg/client/vct/client.go
- pkg/client/vct/client_test.go
- pkg/controller/command/command.go
- pkg/controller/command/command_test.go
- pkg/controller/command/models.go
- pkg/controller/rest/models.go
- pkg/controller/rest/operation.go
- pkg/controller/rest/operation_test.go
- test/bdd/features/rest_controller.feature
- test/bdd/fixtures/vct/contexts/ld-contexts.json
- test/bdd/fixtures/vct/docker-compose.yml
- test/bdd/pkg/controller/rest/rest_controller_steps.go
Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>
> feat: JSON-LD context providers support

- cmd/vct/startcmd/start.go
- go.mod
- go.sum
- scripts/generate_test_keys.sh
- test/bdd/fixtures/vct/docker-compose.yml
Signed-off-by: Volodymyr Kubiv <volodymyr.kubiv@euristiq.com>
> chore: update afgo version

- cmd/vct/startcmd/start.go
> fix: enable http2 in client

- pkg/storage/memory/provider.go
> chore: remove not used logs

- go.mod
- go.sum
> chore: update to latest aries

- cmd/vct/startcmd/start.go
- cmd/vct/startcmd/start_test.go
- go.mod
- go.sum
> chore: add aws metrics

- cmd/vct/startcmd/start.go
- go.mod
- go.sum
> chore: fix postgres conn string

- .github/workflows/build.yml
> chore: add sonarcloud github action step

- .github/workflows/build.yml
- .github/workflows/sonar.yml
> chore: use sonar token

- cmd/vct/startcmd/start.go
- cmd/vct/startcmd/start_test.go
- pkg/client/vct/client.go
- pkg/client/vct/client_test.go
- test/bdd/fixtures/vct/docker-compose.yml
- test/bdd/pkg/controller/rest/rest_controller_steps.go
> chore: add api token

- cmd/vct/startcmd/start.go
- cmd/vct/startcmd/start_test.go
- test/bdd/fixtures/vct/docker-compose.yml
> chore: create initial db for postgres

- cmd/vct/startcmd/start.go
- go.mod
- go.sum
- test/bdd/fixtures/vct/docker-compose.yml
> fix: postgres initial db

- pkg/storage/postgres/schema/storage.sql
> fix: trillian postgres storage public schema

- .github/workflows/build.yml
> chore: switch version-fragment to rc

- Makefile
> chore: fix comment

- pkg/client/vct/client.go
- pkg/client/vct/client_test.go
> feat: add health check method for vct client

- cmd/vct/startcmd/start.go
- internal/pkg/ldcontext/testdata/anchor-v1.json
> chore: update anchor-v1 context

- internal/pkg/ldcontext/testdata/anchor-v1.json
Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>
> fix: Activity anchors context

- cmd/vct/startcmd/start.go
- cmd/vct/startcmd/start_internal_test.go
- go.mod
- go.sum
- pkg/controller/command/command.go
- pkg/controller/command/command_test.go
Signed-off-by: Derek Trider <Derek.Trider@securekey.com>
> feat: Update Aries-Framework-Go, update Aries KMS calls

- cmd/vct/startcmd/start.go
- cmd/vct/startcmd/start_test.go
- pkg/client/vct/client.go
- pkg/client/vct/client_test.go
- pkg/controller/command/command.go
- pkg/controller/command/command_test.go
- pkg/controller/command/handler.go
- pkg/controller/errors/errors.go
- pkg/controller/rest/models.go
- pkg/controller/rest/operation.go
- pkg/controller/rest/operation_test.go
- test/bdd/features/rest_controller.feature
- test/bdd/fixtures/vct/docker-compose.yml
- test/bdd/pkg/controller/rest/rest_controller_steps.go
Also, changed the webfinger resource ID to be the full path of the ledger.
closes #123
Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>
> fix: Move .well-known to the root

- cmd/internal/serverutil/serverutil.go
- cmd/log_server/main.go
- cmd/log_signer/main.go
- cmd/vct/main.go
- cmd/vct/startcmd/start.go
- go.mod
- go.sum
- internal/pkg/cmdutil/cmdutil.go
- internal/pkg/cmdutil/cmdutil_test.go
- internal/pkg/log/logger.go
- internal/pkg/log/logger_test.go
- internal/pkg/tlsutil/certpool.go
- internal/pkg/tlsutil/certpool_test.go
- internal/pkg/tlsutil/tlsutil.go
- internal/pkg/tlsutil/tlsutil_test.go
- pkg/controller/rest/operation.go
- pkg/log/log.go
- pkg/log/log_test.go
- pkg/storage/postgres/admin_storage.go
- pkg/storage/postgres/testdb/testdb.go
- test/bdd/bddtests_test.go
- test/bdd/pkg/controller/rest/rest_controller_steps.go
Also replaced logger with go.uber.org/zap.
closes #127
Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>
> chore: Removed dependency on edge-core

- cmd/vct/startcmd/start.go
- test/bdd/fixtures/vct/docker-compose.yml
> chore: get aws region from key ID
